### ISSUE TITLE
Snowflake Connector for Python Required on Apple Silicon Mac

### ISSUE THREAD

**Issue by minus34** [snowflakedb/qgis-snowflake-connector#54]
Not sure if this affects Windows users as well (unable to test).

I got the error below trying to load the plugin in QGIS 3.40.1 on my M2 MacBook (running macOS 14.7.1).

The workaround was to manually install the Snowflake Connector for Python in the QGIS Python env using:

`/Applications/QGIS.app/Contents/MacOS/bin/python3.9 -m pip install snowflake-connector-python`

**QGIS details**

QGIS version | 3.40.1-Bratislava
QGIS code revision | 989853a7a31
 
Libraries
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 14.7
 
Active Python plugins
qgis2web | 3.24.0
valhalla | 2.5.0
processing | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

**Error**

Couldn't load plugin 'qgis-snowflake-connector' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'snowflake' 
Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 426, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/s57405/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis-snowflake-connector/__init__.py", line 58, in classFactory
    from .qgis_snowflake_connector import QGISSnowflakeConnectorPlugin
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 966, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/s57405/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis-snowflake-connector/qgis_snowflake_connector.py", line 56, in 
    from .providers.sf_metadata_provider import SFMetadataProvider
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 966, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/s57405/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis-snowflake-connector/providers/sf_metadata_provider.py", line 5, in 
    from .sf_vector_data_provider import SFVectorDataProvider
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 966, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/s57405/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis-snowflake-connector/providers/sf_vector_data_provider.py", line 17, in 
    from ..helpers.data_base import check_from_clause_exceeds_size
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 966, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/s57405/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis-snowflake-connector/helpers/data_base.py", line 3, in 
    from ..managers.sf_connection_manager import SFConnectionManager
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 966, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/s57405/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis-snowflake-connector/managers/sf_connection_manager.py", line 3, in 
    import snowflake.connector
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 966, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'snowflake'

Python version: 3.9.5 (default, Sep 10 2021, 16:18:19) [Clang 12.0.5 (clang-1205.0.22.11)] 
QGIS version: 3.40.1-Bratislava Bratislava, 989853a7a31 

Python Path:
/Applications/QGIS.app/Contents/MacOS/../Resources/python
/Users/s57405/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/s57405/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pandas-1.3.3-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/statsmodels-0.11.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/rasterio-1.1.5-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/cftime-1.2.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/lib-dynload
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/netCDF4-1.5.4-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Pillow-7.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/patsy-0.5.1-py3.9.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numpy-1.20.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/geopandas-0.8.1-py3.9.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/scipy-1.5.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pyproj-3.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/matplotlib-3.3.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python39.zip
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Rtree-0.9.7-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/GDAL-3.3.2-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Fiona-1.8.13.post1-py3.9-macosx-10.13.0-x86_64.egg
/Users/s57405/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/s57405/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins

**Comment by sfc-gh-obielov** [comment]
@minus34 what Connector Plugin version do you use?

**Comment by minus34** [comment]
That would help - 0.9.0

**Comment by sfc-gh-obielov** [comment]
@minus34  This should be fixed in 1.0.2. Please install it and let me know if you still face the issue

**Comment by minus34** [comment]
Deleted QGIS application and the Application Support folder and reinstalled QGIS 3.4.

Installing v1.0.2 of the plugin still generated the same errror unfortunately:


Couldn't load plugin 'qgis-snowflake-connector' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'snowflake' 
Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 478, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/s57405/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis-snowflake-connector/__init__.py", line 59, in classFactory
    from .qgis_snowflake_connector import QGISSnowflakeConnectorPlugin
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/s57405/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis-snowflake-connector/qgis_snowflake_connector.py", line 56, in 
    from .providers.sf_metadata_provider import SFMetadataProvider
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/s57405/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis-snowflake-connector/providers/sf_metadata_provider.py", line 6, in 
    from .sf_vector_data_provider import SFVectorDataProvider
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/s57405/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis-snowflake-connector/providers/sf_vector_data_provider.py", line 15, in 
    from .sf_feature_iterator import SFFeatureIterator
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/s57405/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis-snowflake-connector/providers/sf_feature_iterator.py", line 11, in 
    from ..helpers.data_base import limit_size_for_type
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/s57405/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis-snowflake-connector/helpers/data_base.py", line 5, in 
    from ..managers.sf_connection_manager import SFConnectionManager
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/s57405/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis-snowflake-connector/managers/sf_connection_manager.py", line 3, in 
    import snowflake.connector
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'snowflake'


Python version: 3.9.5 (default, Sep 10 2021, 16:18:19) [Clang 12.0.5 (clang-1205.0.22.11)] 
QGIS version: 3.40.3-Bratislava Bratislava, 2a274ab7754 

Python Path:
/Applications/QGIS.app/Contents/MacOS/../Resources/python
/Users/s57405/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/s57405/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/lib-dynload
/Applications/QGIS.app/Contents/MacOS/lib/python39.zip
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numpy-1.20.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/netCDF4-1.5.4-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/patsy-0.5.1-py3.9.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Rtree-0.9.7-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pandas-1.3.3-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/geopandas-0.8.1-py3.9.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Pillow-7.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/cftime-1.2.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pyproj-3.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/scipy-1.5.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/GDAL-3.3.2-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/rasterio-1.1.5-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Fiona-1.8.13.post1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/statsmodels-0.11.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/matplotlib-3.3.0-py3.9-macosx-10.13.0-x86_64.egg
/Users/s57405/Library/Application Support/QGIS/QGIS3/profiles/default/python

**Comment by minus34** [comment]
Have tested on my personal MacBook (same MacBook & macOS version) and it installed fine.

Conclusion is that my work's always on proxy (Netskope) is somehow interfering with Python packge installs even though my work MacBook is configured to allow package installs (command line package installs work fine). Another possibility is our malware scanners are blocking it.
